import { createNavigation } from 'next-intl/navigation';
import { routing } from '@/i18n/routing.ts';

/**
 * Locale-aware navigation, generated by next-intl from the shared `routing`
 * config. `Link`/`useRouter`/`usePathname` (client) and `getPathname`/`redirect`
 * (usable server-side too) automatically add or strip the locale prefix (en at
 * the root, vi under `/vi`): `usePathname()` returns the locale-agnostic
 * ("logical") path, and `useRouter().replace(path, { locale })` switches language.
 *
 * NOTE: this module is safe to import from Server Components (e.g. for
 * `getPathname`), so it must NOT pull in client-only hooks like `useParams` -
 * import those straight from `next/navigation` in the client component instead.
 */
export const { Link, redirect, usePathname, useRouter, getPathname } = createNavigation(routing);
