import { useParams as useNextParams } from 'next/navigation';
import { createNavigation } from 'next-intl/navigation';
import { routing } from '@/i18n/routing.ts';

/**
 * Locale-aware navigation, generated by next-intl from the shared `routing`
 * config. `Link`/`useRouter`/`usePathname`/`redirect`/`getPathname` automatically
 * add or strip the locale prefix (en at the root, vi under `/vi`): `usePathname()`
 * returns the locale-agnostic ("logical") path, and `useRouter().replace(path,
 * { locale })` switches language.
 */
export const { Link, redirect, usePathname, useRouter, getPathname } = createNavigation(routing);

export type RouteParams = Record<string, string | undefined>;

/** Route params from the matched dynamic segments (lang, level, track, ...). */
export function useParams<T extends RouteParams = RouteParams>(): T {
  return useNextParams() as T;
}
