/**
 * One-off generator: downloads per-stroke SVG path data for every single kana
 * from KanjiVG (CC BY-SA 3.0) and writes it to `src/constants/kana-strokes.ts`.
 * Run with: tsx scripts/fetch-kana-strokes.ts
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { hiraganaChartRows, katakanaChartRows } from '@/constants/alphabet-charts.ts';
import type { AlphabetCell } from '@/constants/gojuon.ts';

const outFile = join(dirname(fileURLToPath(import.meta.url)), '../src/constants/kana-strokes.ts');

const cells = [...hiraganaChartRows, ...katakanaChartRows].flatMap((row) =>
  [...(row.seion ?? []), ...(row.dakuten ?? []), ...(row.handakuten ?? [])].filter(
    (cell): cell is AlphabetCell => cell != null
  )
);

// Only single code-point kana (KanjiVG has no combined yoon glyphs).
const chars = Array.from(
  new Set(cells.map((cell) => cell.char).filter((char) => Array.from(char).length === 1))
);

async function fetchStrokes(char: string): Promise<string[] | null> {
  const codepoint = char.codePointAt(0)!.toString(16).padStart(5, '0');
  const url = `https://cdn.jsdelivr.net/gh/KanjiVG/kanjivg@master/kanji/${codepoint}.svg`;
  const response = await fetch(url);

  if (!response.ok) {
    return null;
  }

  const svg = await response.text();
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((match) => match[1]);

  return paths.length > 0 ? paths : null;
}

async function run() {
  const data: Record<string, string[]> = {};
  const concurrency = 8;
  let cursor = 0;
  let missing = 0;

  async function worker() {
    for (let index = cursor++; index < chars.length; index = cursor++) {
      const char = chars[index];
      const strokes = await fetchStrokes(char);

      if (strokes) {
        data[char] = strokes;
      } else {
        missing += 1;
        console.warn(`No KanjiVG data for ${char}`);
      }
    }
  }

  await Promise.all(Array.from({ length: concurrency }, () => worker()));

  // Stable key order for a clean diff.
  const ordered = Object.fromEntries(
    Object.keys(data)
      .sort()
      .map((key) => [key, data[key]])
  );

  const file = `// Auto-generated by scripts/fetch-kana-strokes.ts - do not edit by hand.
// Per-stroke SVG path data from KanjiVG (CC BY-SA 3.0), viewBox 0 0 109 109.

export const KANA_STROKE_VIEWBOX = 109;

export const kanaStrokes: Record<string, string[]> = ${JSON.stringify(ordered, null, 2)};
`;

  writeFileSync(outFile, file);
  console.log(`Wrote ${Object.keys(ordered).length} kana (${missing} missing) to kana-strokes.ts`);
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
